"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies


class Assignee(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.info = parsing_info
        self.entity = None
        self.id = None
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["Assignee"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "EntityWithCoord":
            raise NotImplementedError("EntityWithCoord")
        elif rule == "Entity":
            self.entity = parsing_info
            self.id = parsing_info.id

