"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxInterpretation import AuxInterpretation
from classes.AuxRuleDependencies import AuxRuleDependencies


class AxiomBlock(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.info = parsing_info
        self.predicate = None
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["AxiomBlock"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "VariableSpecificationList":
            raise NotImplementedError("VariableSpecificationList")
        elif rule == "Predicate":
            self.predicate = parsing_info.predicate
        elif rule == "LeftBrace":
            self.stop_aggregation = True
