"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies


class CompoundPredicate(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.info = parsing_info
        self.predicate = None
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["CompoundPredicate"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "Conjunction":
            self.predicate = parsing_info.predicate
        elif rule == "Disjunction":
            self.predicate = parsing_info.predicate
        elif rule == "Implication":
            self.predicate = parsing_info.predicate
        elif rule == "Equivalence":
            self.predicate = parsing_info.predicate
        elif rule == "ExclusiveOr":
            self.predicate = parsing_info.predicate
        elif rule == "Negation":
            self.predicate = parsing_info.predicate
        elif rule == "All":
            self.predicate = parsing_info.predicate
        elif rule == "Exists":
            self.predicate = parsing_info.predicate
        self.stop_aggregation = True

