"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxSTType import AuxSTType
from poc.classes.AuxBits import AuxBits
from poc.classes.AuxRuleDependencies import AuxRuleDependencies


class ContextIndexHeader(AuxInterpretation):
    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.indexType = AuxSTType(i)
        self.indexType.type_mod = None
        self.indexType.type_pattern = AuxBits.indexBit
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["IndexHeader"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "index":
            self.indexType.id = rule
        elif rule == "ind":
            self.indexType.id = rule
        self.stop_aggregation = True

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextIndexHeader(i)
        new_info.indexType.zto = i.last_positions_by_rule['IndexHeader'].pos_to_str()
        new_info.indexType.zfrom = i.corrected_zpos_by(new_info.indexType.zto, len(new_info.indexType.id))
        i.parse_list.append(new_info)
