"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.Disjunction import Disjunction


class ContextDisjunction:
    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = Disjunction(i.parse_list, parsing_info)
        # order the children like they appear the FPL source code, not like they were parsed
        new_info.predicate.children = reversed(new_info.predicate.children)
        i.parse_list.append(new_info)
