"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTLocalization import AuxSTLocalization


class ContextLocalization(AuxInterpretation):
    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.localization = AuxSTLocalization(parsing_info)
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["Localization"] +
                                      AuxRuleDependencies.dep["TranslationList"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "Predicate":
            self.localization.register_child(parsing_info.predicate)  # noqa
            self.stop_aggregation = True
        elif rule == "Translation":
            self.localization.register_child(parsing_info.transl)  # noqa

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextLocalization(i.parse_list, parsing_info)
        new_info.localization.children = reversed(new_info.localization.children)
        i.parse_list.append(new_info)
