"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTVarSpecList import AuxSTVarSpecList
from poc.classes.AuxSTStatement import AuxSTStatement
from poc.classes.AuxSTConstants import AuxSTConstants


class ContextDefaultResult(AuxInterpretation):

    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.statement = AuxSTStatement(AuxSTConstants.case_default, i)
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["DefaultResult"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "else":
            self.stop_aggregation = True
        elif rule == "StatementList":
            stmt_list = AuxSTVarSpecList()
            for stmt in reversed(parsing_info.statement_list):  # noqa
                stmt.parent = stmt_list
            self.statement.register_child(stmt_list)

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextDefaultResult(i)
        i.parse_list.append(new_info)
