"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSymbolTable import AuxSymbolTable
from poc.classes.AuxSTPredicate import AuxSTPredicate


class ContextKeysOfVariadicVariable(AuxInterpretation):

    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.predicate = AuxSTPredicate(AuxSymbolTable.variadic_var, i)
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["KeysOfVariadicVariable"] +
                                      ["VariableList", "Identifier"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "Variable":
            self.predicate.register_child(parsing_info.var)  # noqa
            self.predicate.set_id(parsing_info.var.id + "$")
            self.stop_aggregation = True
        elif rule == "VariableList":
            self.predicate.register_child(parsing_info.var_list[0].var)  # noqa
            self.predicate.set_id(parsing_info.var_list[0].var.id + "$")
            self.stop_aggregation = True
        elif rule == "Identifier":
            self.predicate.register_child(parsing_info.predicate)  # noqa
            self.predicate.set_id(parsing_info.predicate.id + "$")
            self.stop_aggregation = True

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextKeysOfVariadicVariable(i)
        i.parse_list.append(new_info)
