"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AssertionStatement import AssertionStatement
from poc.classes.AuxSymbolTable import AuxSymbolTable


class ContextAssertionStatement:
    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = AssertionStatement(i.parse_list, parsing_info)
        current_node = i.touch_node()
        AuxSymbolTable.add_statement_to_node(current_node, new_info.predicate)
        i.parse_list.append(new_info)
