"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxSTArgumentParam import AuxSTArgumentParam
from poc.classes.AuxRuleDependencies import AuxRuleDependencies


class ContextArgumentParam(AuxInterpretation):
    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.predicate = AuxSTArgumentParam(i)
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["ArgumentParam"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "ArgumentIdentifier":
            self.predicate.id = parsing_info.id

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextArgumentParam(i)
        i.parse_list.append(new_info)

