"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTStatementCaseSome import AuxSTStatementCaseSome
from poc.classes.AuxSTVarSpecList import AuxSTVarSpecList


class ContextConditionFollowedByResult(AuxInterpretation):

    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.statement = AuxSTStatementCaseSome(i)
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["ConditionFollowedByResult"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "case":
            self.stop_aggregation = True
        elif rule == "Predicate":
            self.statement.register_child(parsing_info.predicate)  # noqa
            self.statement.zfrom = parsing_info.predicate.zfrom
        elif rule == "StatementList":
            stmt_list = AuxSTVarSpecList()
            for stmt in parsing_info.statement_list:  # noqa
                stmt.parent = stmt_list
            self.statement.register_child(stmt_list)

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextConditionFollowedByResult(i)
        new_info.statement.children = reversed(new_info.statement.children)
        i.parse_list.append(new_info)
