"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTPredicate import AuxSTPredicate
from poc.classes.AuxSymbolTable import AuxSymbolTable


class ContextCoord(AuxInterpretation):

    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.predicate = AuxSTPredicate(AuxSymbolTable.uninterpreted, i)
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["Coord"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "Assignee":
            if parsing_info.predicate is not None:  # noqa
                self.predicate = parsing_info.predicate  # noqa
            self.stop_aggregation = True
        elif rule == "PrimePredicate":
            if parsing_info.predicate is not None:  # noqa
                self.predicate = parsing_info.predicate  # noqa
            self.stop_aggregation = True

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextCoord(i)
        i.parse_list.append(new_info)
