"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies


class ContextVariableSpecification(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.named_var_declaration = None
        self.statement = None
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["VariableSpecification"],
                                      self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "Statement":
            self.statement = parsing_info.statement  # noqa
        elif rule == "NamedVariableDeclaration":
            self.named_var_declaration = parsing_info

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextVariableSpecification(i.parse_list, parsing_info)
        i.parse_list.append(new_info)
