"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxSymbolTable import AuxSymbolTable
from poc.classes.AuxSTPredicate import AuxSTPredicate
from poc.classes.AuxRuleDependencies import AuxRuleDependencies


class ContextPremiseBlock(AuxInterpretation):

    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.predicate = AuxSTPredicate(AuxSymbolTable.pre, i)
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["PremiseBlock"] +
                                      AuxRuleDependencies.dep["PremiseHeader"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule in AuxRuleDependencies.dep["PremiseHeader"]:
            self.stop_aggregation = True
        elif rule == "Predicate":
            self.predicate.register_child(parsing_info.predicate)  # noqa

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextPremiseBlock(i)
        new_info.predicate.zto = i.last_positions_by_rule['PremiseBlock'].pos_to_str()
        new_info.predicate.zfrom = i.corrected_position('PremiseHeader')
        i.parse_list.append(new_info)
