"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.PredicateDefinitionBlock import PredicateDefinitionBlock


class ContextPredicateDefinitionBlock:
    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        p_info = PredicateDefinitionBlock(i.parse_list, parsing_info)
        i.parse_list.append(p_info)

