"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxSTVarSpecList import AuxSTVarSpecList
from poc.classes.AuxSTProofArguments import AuxSTProofArguments


class ContextProofBlock(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        # specification list is optional in the grammar and we initialize it in any case
        self.variable_spec = AuxSTVarSpecList()
        self.proof_arguments = AuxSTProofArguments()
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["ProofBlock"] +
                                      AuxRuleDependencies.dep["ProofArgumentList"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "LeftBrace":
            self.stop_aggregation = True
        elif rule == "VariableSpecificationList":
            self.variable_spec = parsing_info.variable_spec  # noqa
        elif rule == "ProofArgument":
            parsing_info.proof_argument.parent = self.proof_arguments  # noqa

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextProofBlock(i.parse_list, parsing_info)
        new_info.proof_arguments.children = reversed(new_info.proof_arguments.children)
        i.parse_list.append(new_info)
