"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTCoords import AuxSTCoords


class ContextCoordInType(AuxInterpretation):

    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.predicate = AuxSTCoords(i)
        self.predicate.zto = i.last_positions_by_rule['CoordInType'].pos_to_str()
        self.predicate.zfrom = i.last_positions_by_rule['LeftBracket'].pos_to_str()
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["CoordInType"] + ["Identifier"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "PredicateWithArguments":
            self.predicate.register_child(parsing_info.predicate)  # noqa
        elif rule == "Variable":
            self.predicate.register_child(parsing_info.predicate)  # noqa
        elif rule == "IndexValue":
            self.predicate.register_child(parsing_info.predicate)  # noqa
        elif rule == "Identifier":
            self.predicate.register_child(parsing_info.predicate)  # noqa
        self.stop_aggregation = True

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextCoordInType(i)
        i.parse_list.append(new_info)
