"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxContext import AuxContext
from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.LeftBound import LeftBound
from poc.classes.RightBound import RightBound


class ContextBound:
    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        i.parse_list.append(parsing_info)

    @staticmethod
    def start(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        i.context.push_context(AuxContext.bound, i.get_debug_parsing_info(parsing_info))
        new_info = LeftBound(i.parse_list, parsing_info)
        ContextBound.dispatch(i, new_info)

    @staticmethod
    def stop(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        i.context.pop_context([AuxContext.bound], i.get_debug_parsing_info(parsing_info))
        new_info = RightBound(i.parse_list, parsing_info)
        ContextBound.dispatch(i, new_info)

