"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTExtension import AuxSTExtension


class ContextExtensionBlock(AuxInterpretation):
    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.extension = AuxSTExtension(i)
        self._extension_regex = ""
        self._extension_name = ""
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["ExtensionBlock"] +
                                      AuxRuleDependencies.dep["ExtensionHeader"] +
                                      AuxRuleDependencies.dep["ExtensionContent"] +
                                      AuxRuleDependencies.dep["ExtensionTail"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "ExtensionName":
            cst = parsing_info.get_cst()
            self._extension_name = cst[0] + cst[1]
        elif rule == "ExtensionRegex":
            self._extension_regex = parsing_info.get_cst()

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextExtensionBlock(i)
        new_info.extension.set_extension_content(new_info._extension_name, new_info._extension_regex)
        i.parse_list.append(new_info)
