"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxSymbolTable import AuxSymbolTable
from poc.classes.AuxSTStatement import AuxSTStatement
from poc.classes.AuxRuleDependencies import AuxRuleDependencies


class ContextAssignmentStatement(AuxInterpretation):

    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.statement = AuxSTStatement(AuxSymbolTable.statement_assign, i)
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["AssignmentStatement"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "Assignee":
            self.statement.register_child(parsing_info.predicate)  # noqa
            self.stop_aggregation = True
        elif rule == "Predicate":
            self.statement.register_child(parsing_info.predicate)  # noqa

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextAssignmentStatement(i)
        new_info.statement.children = reversed(new_info.statement.children)
        i.parse_list.append(new_info)
