"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTVarSpecList import AuxSTVarSpecList


class ContextDefinitionProperty(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.building_block = AuxSTVarSpecList()
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["DefinitionProperty"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "ClassInstance":
            self.building_block = parsing_info.building_block  # noqa
        elif rule == "PredicateInstance":
            self.building_block = parsing_info.building_block  # noqa
        elif rule == "FunctionalTermInstance":
            self.building_block = parsing_info.building_block  # noqa

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextDefinitionProperty(i.parse_list, parsing_info)
        i.parse_list.append(new_info)

