"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTStatementLoop import AuxSTStatementLoop


class ContextLoopStatement(AuxInterpretation):
    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.statement = AuxSTStatementLoop(i)
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["LoopStatement"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "loop":
            self.stop_aggregation = True
        elif rule == "RangeOrLoopBody":
            self.statement.register_child(parsing_info.varCounter)
            self.statement.register_child(parsing_info.varRange)
            for statement in parsing_info.statement_list:
                self.statement.register_child(statement)

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextLoopStatement(i)
        i.parse_list.append(new_info)

