"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTStatementCase import AuxSTStatementCase


class ContextCaseStatement(AuxInterpretation):

    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.statement = AuxSTStatementCase(i)
        self.aggregate_previous_rules(i.parse_list, AuxRuleDependencies.dep["CaseStatement"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "cases":
            self.stop_aggregation = True
        elif rule == "ConditionFollowedByResultList":
            for cfr in parsing_info.cfr_list:
                self.statement.register_child(cfr.statement)  # noqa
        elif rule == "DefaultResult":
            self.statement.register_child(parsing_info.statement)  # noqa

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextCaseStatement(i)
        new_info.statement.children = reversed(new_info.statement.children)
        i.parse_list.append(new_info)
