"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTConstructor import AuxSTConstructor
from poc.classes.AuxSymbolTable import AuxSymbolTable
from poc.classes.AuxSTConstants import AuxSTConstants


class ContextConstructorBlock(AuxInterpretation):

    def __init__(self, i: AuxISourceAnalyser):
        super().__init__(i.ast_info, i.errors)
        self.predicate_with_args = None
        self.variable_spec = None
        self.aggregate_previous_rules(i.parse_list,
                                      AuxRuleDependencies.dep["ConstructorBlock"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "PredicateWithArguments":
            self.predicate_with_args = parsing_info.predicate
        elif rule == "VariableSpecificationList":
            self.variable_spec = parsing_info.variable_spec  # noqa

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextConstructorBlock(i)
        i.parse_list.append(new_info)
