"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSymbolTable import AuxSymbolTable
from poc.classes.AuxSTStatement import AuxSTStatement


class ContextAssertionStatement(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.statement = AuxSTStatement(AuxSymbolTable.statement_assert, parsing_info)
        self.statement.type = AuxSymbolTable.statement_assert
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["AssertionStatement"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "assert":
            self.stop_aggregation = True
        elif rule == "Predicate":
            self.statement.register_child(parsing_info.predicate)  # noqa

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextAssertionStatement(i.parse_list, parsing_info)
        i.parse_list.append(new_info)
