"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser
from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSTProofArgument import AuxSTProofArgument


class ContextProofArgument(AuxInterpretation):
    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.proof_argument = AuxSTProofArgument(parsing_info)
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["ProofArgument"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "ArgumentIdentifier":
            self.proof_argument.id = parsing_info.id  # noqa
            self.stop_aggregation = True
        elif rule == "Justification":
            self.proof_argument.register_child(parsing_info.justification)  # noqa
        elif rule == "ArgumentInference":
            self.proof_argument.register_child(parsing_info.proof_argument)  # noqa

    @staticmethod
    def dispatch(i: AuxISourceAnalyser, parsing_info: AuxInterpretation):
        new_info = ContextProofArgument(i.parse_list, parsing_info)
        i.parse_list.append(new_info)

