"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies


class IsOperator(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.info = parsing_info
        self.identifier = None
        self.general_type = None
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["IsOperator"] + ["IdStartsWithSmallCase"],
                                      self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "Identifier":
            self.identifier = parsing_info
        elif rule == "GeneralType":
            self.general_type = parsing_info
        elif rule == "IdStartsWithSmallCase":
            if self.general_type is not None and self.identifier is not None:
                self.stop_aggregation = True
