"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies
from poc.classes.AuxSymbolTable import AuxSymbolTable
from poc.classes.AuxPredicate import AuxPredicate


class PredicateWithArguments(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.info = parsing_info
        self.predicate = AuxPredicate(AuxSymbolTable.predicate_with_arguments)
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["PredicateWithArguments"] +
                                      AuxRuleDependencies.dep["PredicateList"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "Identifier":
            self.id = parsing_info.id
            self.stop_aggregation = True
        elif rule == "Predicate":
            self.predicate.register_child(parsing_info.predicate)
