"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""

from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies


class RulesOfInferenceBlock(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        self.clone(parsing_info)
        self.info = parsing_info
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["RulesOfInferenceBlock"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "InferenceHeader":
            pass
        if rule == "CW":
            pass
        if rule == "LeftBrace":
            pass
        if rule == "RuleOfInferenceList":
            pass
        if rule == "RightBrace":
            pass
