"""
This file was generated by the tool TatSuSAG (the TatSu syntax analyser generator)
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
"""


from poc.classes.AuxInterpretation import AuxInterpretation
from poc.classes.AuxRuleDependencies import AuxRuleDependencies


class CTypeWithCoord(AuxInterpretation):

    def __init__(self, parse_list: list, parsing_info: AuxInterpretation):
        super().__init__(parsing_info.get_ast_info(), parsing_info.get_errors())
        self.info = parsing_info
        self.type = None
        self.left_bound_included = True
        self.right_bound_included = True
        self.aggregate_previous_rules(parse_list,
                                      AuxRuleDependencies.dep["TypeWithCoord"], self.rule_aggregator)

    def rule_aggregator(self, rule: str, parsing_info: AuxInterpretation):
        if rule == "Type":
            self.type = parsing_info
        elif rule == "LeftBound":
            self.left_bound_included = parsing_info.bound_included
        elif rule == "IW":
            pass
        elif rule == "RangeInType":
            pass
        elif rule == "CoordInType":
            pass
        elif rule == "RightBound":
            self.right_bound_included = parsing_info.bound_included

