import unittest
from parameterized import parameterized
from poc.util.fplutil import Utils
from poc.fplinterpreter import FplInterpreter
import os
from poc.classes.AuxISourceAnalyser import AuxISourceAnalyser

"""
Note: FPL parser is autogenerated through the TatSu package. Therefore, we do not test any FPL syntax errors.
"""


class FplAmbiguousSignatureTests(unittest.TestCase):
    path = None
    util = None
    path_to_grammar = None

    @classmethod
    def setUpClass(cls):
        cls.path = os.path.normpath(os.path.abspath(__file__))
        if os.path.isfile(cls.path):
            cls.path = os.path.dirname(cls.path)
        cls.path_to_grammar = os.path.join(cls.path, "../../../grammar")
        cls.path_to_usecases = os.path.join(cls.path)
        cls.util = Utils()
        cls.fpl_parser = cls.util.get_parser(cls.path_to_grammar + "/fpl_tatsu_format.ebnf")

    @parameterized.expand([
        ("test_FplAmbiguousSignature_01.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_02.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_03.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_04.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_05.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_06.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_07.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_08.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_09.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_10.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_11.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_12.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_13.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_14.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_15.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_16.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_17.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_18.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_19.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_20.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_21.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_22.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_23.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_24.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_25.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_26.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_27.fpl", "SE0170"),
        ("test_FplAmbiguousSignature_28.fpl", "SE0170"),
    ])
    def test_errors(self, use_case, diagnose_id):
        path_to_use_cases = os.path.join(self.path_to_usecases, use_case)
        interpreter = FplInterpreter(self.fpl_parser, path_to_use_cases)
        result = Utils.get_code_and_expected(self.path_to_usecases, use_case)
        interpreter.syntax_analysis(path_to_use_cases)
        interpreter.semantic_analysis()
        if AuxISourceAnalyser.verbose:
            interpreter.get_error_mgr().print_errors()
        # the error is the same as in the use case file
        self.assertTrue(Utils.check_if_error_occurs(result[1], interpreter.get_error_mgr(), diagnose_id))
