import unittest
from parameterized import parameterized
from poc.classes.AuxBits import AuxBits

"""
Tests of FPL related (transformer) errors.
Note: FPL parser is autogenerated through the TatSu package. Therefore, we do not test any FPL syntax errors.
"""


class AuxBitsTests(unittest.TestCase):

    @parameterized.expand([
        (AuxBits.objectBit, AuxBits.is_object),
        (AuxBits.inbuiltBit, AuxBits.in_built),
        (AuxBits.extensionBit, AuxBits.is_extension),
        (AuxBits.predicateBit, AuxBits.is_predicate),
        (AuxBits.classBit, AuxBits.is_class),
        (AuxBits.indexBit, AuxBits.is_index),
        (AuxBits.templateBit, AuxBits.is_generic),
        (AuxBits.functionalTermBit, AuxBits.is_functional_term),
    ])
    def test_possibilities_true(self, pattern_int: int, checking_function):
        self.assertTrue(checking_function(pattern_int))

    @parameterized.expand([
        (AuxBits.objectBit | AuxBits.inbuiltBit, AuxBits.is_index),
    ])
    def test_possibilities_false(self, pattern_int: int, checking_function):
        self.assertFalse(checking_function(pattern_int))
